# Site settings

title: 如山 | rushanfilm
SEOTitle: 如山【胶片年代】
SUBSTitle: rushanfilm
email: fsux@outlook.com
description: "一个有关胶片摄影、生活、艺术、美图、拍照技巧、胶片相机器材介绍，以及个人胶片摄影作品分享的综合性网站。取景框教会了我们看世界的另一种方式，我们就是爱胶片。拿起相机，拍照吧！"
baseurl: "" # the subpath of your site, e.g. /blog/
keyword: "胶片, 摄影, 拍照, 旅行, 日系, 小清新, 分享, 胶卷, 菲林, 器材, 投稿, 文艺, 胶卷相机, 胶片相机, 胶片摄影"
url: "https://fsux.me" # the base hostname & protocol for your site
author: "如山,rushanfilm"
pygments: true
# Outputting

paginate: 5
paginate_path: /page/:num

# Build settings
markdown: redcarpet
redcarpet:
    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
